### ISSUE TITLE
How to dismiss progress flower dialog programmatically?

### ISSUE THREAD

**Issue by rockstardev8964** [Cloudist/ACProgressLite#1]
I am using this view on http communication in my activity.

progressFlower = new ACProgressFlower.Builder(getActivity())
                .direction(ACProgressConstant.DIRECT_CLOCKWISE)
                .themeColor(Color.WHITE)
                .text("Please wait...")
                .fadeColor(Color.DKGRAY).build();
progressFlower.show();

After get response from server, then run progressFlower.dismiss(), App crashed.

From my debugging, progressFlower is null.

How to dismiss progress flower dialog programmatically?

Best regards.

**Comment by rockstardev8964** [comment]
i fixed myself.

**Comment by sunnykinger** [comment]
could you share how you fixed it?

**Comment by islamYMansour** [comment]
progressFlower.dismiss()
